name: Build and Release
on: push
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - run: npm install -g quicktype

            - run: |
                quicktype \
                  --src-lang schema \
                  fhir.schema.json \
                  --lang cpp \
                  --just-types \
                  --no-boost \
                  --code-format with-struct \
                  --top-level Fhir \
                  --out Fhir.cpp
                  
            - run: echo "$(<Fhir.cpp )"
            
            - name: Release prebuilt
              uses: ncipollo/release-action@v1
              with:
                artifacts: "Fhir.cpp"
                allowUpdates: true
                token: ${{ secrets.GITHUB_TOKEN }}
